version: '3'

services:
  app:
    container_name: app
    build: ./app
    volumes:
     - ./app/source:/django
    ports:
     - 8000:8000
    image: app:django
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      app_net:
        ipv4_address: 172.20.0.3
    depends_on:
      - db
  db:
    image: mariadb:10.7
    container_name: mysql
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - 3333:3306
    environment:
      MYSQL_DATABASE: 'django'
      MYSQL_ROOT_PASSWORD: 'QWERasdf1'
    networks:
      app_net:
        ipv4_address: 172.20.0.2
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
